### ISSUE TITLE
Добавить бейджик с maintainability codecliemate в README.md

### ISSUE THREAD

**Issue by sergio-fry** [sergio-fry/history#38]
пример https://github.com/objectionary/eo?tab=readme-ov-file

**Comment by sergio-fry** [comment]
@railsroger нужно привязать к PR

**Comment by railsroger** [comment]
<img width="897" alt="badges" src="https://github.com/sergio-fry/history/assets/22810549/3513bf8d-3ade-4a53-bb56-7e0b53619bc6">

Вероятнее всего ID не правильный, я протестил на своем тестовом и все работает. Может ты бы смог посмотреть ID вот тут где на скрине.

**Comment by railsroger** [comment]
Тк как TEST REPORTER ID не равно уникальному ID бейджа.
